
	<footer>
		<div class="menu">
			<div class="section">
				<div class="header">Про нас</div>
				<div class="items">
					<a class="item" href="http://luchesk.ua/about-uk.html" title="Про компанію «Лучеськ»">Наш колектив</a>
					<a class="item" href="/works/" title="Приклади робіт компанії «Лучеськ»">Наші роботи</a>
					<a class="item" href="/contacts-ua.html" title="Контакти компанії «Лучеськ»">Контакти</a>
				</div>
			</div>
			<div class="section">
				<div class="header">Допомога</div>
				<div class="items">
					<a class="item" href="http://luchesk.ua/payment-uk.html" title="Умови оплати за товари, придбані у компанії «Лучеськ» та послуги, надані компанією «Лучеськ»">Оплата</a>
					<a class="item" href="http://luchesk.ua/delivery-uk.html" title="Умови доставки замовлень компанією «Лучеськ»">Доставка</a>
					<a class="item" href="http://luchesk.ua/warranty-uk.html" title="Гарантія на товари, придбані у компанії «Лучеськ» та послуги, надані компанією «Лучеськ»">Гарантія</a>
				</div>
			</div>
			<div class="section">
				<div class="header">Проекти</div>
				<div class="items">
					<a class="item" href="/faq/" title="Журнал про каміни «Лучеськ»">Блог</a>
					<a class="item" href="http://club.luchesk.ua/" title="Клуб особливих клієнтів компанії «Лучеськ»">Клуб</a>
					<a class="item" href="//saunabud.com/" title="Інтернет-магазин «Лучеськ» Усе для будівництва та обслуговування сауни та бані">Усе для сауни та лазні</a>
				</div>
			</div>
			<div class="section">
				<div class="header">Послуги</div>
				<div class="items">
					<a class="item" href="http://luchesk.ua/designing_fireplaces-uk.html" title="Проектування камінів у компанії «Лучеськ»">Проектування каміна</a>
					<a class="item" href="http://luchesk.ua/installation_fireplaces-uk.html" title="Монтаж камінів від компанії «Лучеськ»">Монтаж каміна</a>
				</div>
			</div>
		</div>
		<div class="license">
			<div class="terms"><a href="http://luchesk.ua/terms_of_use-uk.html" title="Умови використання інформації, розміщеної на веб-майданчиках компанії «Лучеськ»">Умови використання</a></div>
			<div class="copyright"><span title="Всі права захищені">&copy; 2006— 2020</span> <a href="http://luchesk.ua/" title="Компанія «Лучеськ»">LUCHESK</a></div>
		</div>
		<!--
		<div class="projectBottomFixedString">
			<p class="projectBottomFixedString__profit"><a href="/profit-ua.html">Як отримати вигоду до 5 %</a></p>
		</div>
		-->
		<div class="notification"><div class="message"><span class="sorting"><span class="name">Відсортовано: </span></span><span class="filtering"><span class="name">Знайдено: </span></span><span class="insert"></span></div><div class="link">ПЕРЕЙТИ</div></div>
	</footer>
