
	<footer>
		<div class="license">
			<div class="terms"><a href="http://luchesk.ua/terms_of_use-uk.html" title="Умови використання інформації, розміщеної на веб-майданчиках компанії «Лучеськ»">Умови використання</a></div>
			<div class="copyright"><span title="Всі права захищені">&copy; 2006—2019</span> <a href="http://luchesk.ua/" title="Компанія «Лучеськ»">LUCHESK</a></div>
		</div>
		<div class="notification"><div class="message"><span class="sorting"><span class="name">Відсортовано: </span></span><span class="filtering"><span class="name">Знайдено: </span></span><span class="insert"></span></div><div class="link">ПЕРЕЙТИ</div></div>
	</footer>
