
	<header>
		<div class="zero">
			<div class="container">
				<div class="items">
					<a class="item" href="/contacts-ua.html">Контакти</a>
					<a class="item" href="/delivery-ua.html">Доставка</a>
					<a class="item" href="/payment-ua.html">Оплата</a>
					<a class="item" href="/warranty-ua.html">Гарантія</a>
					<a class="item profit" href="/profit-ua.html">Отримайте вигоду 3—5 %</a>
				</div>
			</div>
		</div>
		<div class="first">
			<div class="container">
				<div class="left">
					<div class="switch"></div>
					<a class="logo" href="/index-ua.html" title="Перейти на головну"></a>
				</div>
				<div class="centre">
					<div class="top">
						<div class="text right">українською</div><!--для російських тут посилання -->
						<a class="icon-switch-left" href="/index-ru.html" lang="ru"></a><!--для російських icon-switch-right -->
						<a class="text left" href="/index-ru.html" lang="ru">по-русски</a><!--для російських тут нема посилання -->
					</div>
					<div class="bottom">
						<div class="search-container">
							<div class="switch"></div>
							<div class="input-block">
								<div class="close-search"></div>
								<input class="input" type="search" placeholder="Хочу знайти">
								<!--
								<div class="clear-search"></div>
								-->
							</div>
							<div class="result-block">
								<div class="items">
									<div class="item group">Топки для каміна</div>
									<div class="item group">Топки з повітряним обігрівом</div>
									<div class="item group">Топки з водяним контуром</div>
									<div class="item keyword">Топка</div>
									<div class="item keyword">Топки Romotop</div>
								</div>
							</div>
						</div>
						<div class="shadow-layer"></div>
					</div>
				</div>
				<div class="right">
					<div class="top">
						<div class="menu user desktop" data-user="not-logged" data-present>
							<div class="switch" data-user="not-logged"><div class="icon"></div><div>Увійти</div></div>
							<div class="items" data-user="not-logged">
								<div class="text">Увійти за допомогою електронної пошти</div>
								<form action="/" name="form-user-desktop">
									<div class="form-input">
										<label for="form-user-desktop-email">Електронна пошта</label>
										<input class="block" type="email" name="form-user-desktop-email" id="form-user-desktop-email" autocomplete="off" required>
										<div class="input-error-text" data-error-type="1">Вкажіть адресу електронної пошти</div>
									</div>
									<button type="submit" class="button type1 green">Отримати доступ</button>
								</form>
								<div class="text">або через соціальну мережу</div>
								<button type="button" class="button type1 facebook">Facebook</button>
								<button type="button" class="button type1 google">Google</button>
							</div>
							<div class="switch" data-user="logged"><div class="icon"></div><div>Профіль</div></div>
							<div class="items" data-user="logged">
								<div class="item user-name"></div>
								<div class="item link left-icon profile"><a class="link" href="/user-ua.html">Обліковий запис</a></div>
								<div class="item link left-icon profits"><a href="user-cabinet-profits-ua.html">Мої вигоди</a></div>
								<div class="item link left-icon bookmarks"><a href="bookmarks-ua.html">Вибране</a></div>
								<div class="item link left-icon history"><a class="link" href="/history-ua.html">Історія замовлень</a></div>
								<div class="item link left-icon response"><a class="link" href="/response-ua.html">Написати відгук</a></div>
								<div class="item link left-icon exit"><a class="link" href="/">Вийти</a></div>
							</div>
						</div>
						<div class="menu bookmarks">
							<div class="switch"><span class="icon"></span><span class="desktop"> Вибране</span></div>
						</div>
						<div class="menu basket">
							<div class="switch"><span class="icon"></span><span class="desktop"> Кошик</span></div>
						</div>
					</div>
					<div class="bottom">
						<div class="viber"><a class="icon" href="viber://add?number=12345678" title="Viber"></a></div>
						<div class="telegram"><a class="icon" href="https://t.me/voxep" title="Telegram"></a></div>
						<div class="menu contacts" data-present>
							<div class="switch"><div class="icon"></div></div>
							<div class="items">
								<div class="item tel"><a class="link" href="tel:+380995335050">Vodafone: +38 099 533 50 50</a></div>
								<div class="item tel"><a class="link" href="tel:+380985335050">Київстар: +38 098 533 50 50</a></div>
								<div class="item viber"><a class="icon" href="viber://add?number=12345678" title="Viber">Viber</a></div>
								<div class="item telegram"><a class="icon" href="https://t.me/voxep" title="Telegram">Telegram</a></div>
							</div>
						</div>
						<div class="phones">
							<div class="phone"><a href="tel:+380985335050">+38 098 533 50 50</a></div>
							<div class="phone"><a href="tel:+380995335050">+38 099 533 50 50</a></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="second">
			<div class="top-line mobile">
				<a class="logo" href="/index-ua.html" title="Перейти на головну"></a>
			</div>
			<div class="menu language mobile">
				<a class="switch" href="//kamin.lutsk.ua/">рус</a>
			</div>
			<div class="menu help mobile" data-present>
				<div class="switch"><span class="icon"></span></div>
				<div class="items">
					<div class="item link left-icon payment"><a class="link" href="http://luchesk.ua/payment-uk.html">Оплата</a></div>
					<div class="item link left-icon delivery"><a class="link" href="http://luchesk.ua/delivery-uk.html">Доставка товару</a></div>
					<div class="item link left-icon warranty"><a class="link" href="http://luchesk.ua/warranty-uk.html">Гарантія</a></div>
				</div>
			</div>
			<div class="menu user mobile" data-user="not-logged" data-present>
				<div class="switch" data-user="not-logged"><div class="icon"></div><div>Увійти</div></div>
				<div class="items" data-user="not-logged">
					<div class="text">Увійти за допомогою електронної пошти</div>
					<form action="/" name="form-user-mobile">
						<div class="form-input">
							<label for="form-user-mobile-email">Електронна пошта</label>
							<input class="block" type="email" name="form-user-mobile-email" id="form-user-mobile-email" autocomplete="off" required>
							<div class="input-error-text" data-error-type="1">Вкажіть адресу електронної пошти</div>
						</div>
						<button type="submit" class="button type1 green">Отримати доступ</button>
					</form>
					<div class="text">або через соціальну мережу</div>
					<button type="button" class="button type1 facebook">Facebook</button>
					<button type="button" class="button type1 google">Google</button>
				</div>
				<div class="switch" data-user="logged"><div class="icon"></div><div class="item user-name"></div></div>
				<div class="items" data-user="logged">
					<div class="item link left-icon profile"><a class="link" href="/user-ua.html">Обліковий запис</a></div>
					<div class="item link left-icon profits"><a href="user-cabinet-profits-ua.html">Мої вигоди</a></div>
					<div class="item link left-icon bookmarks"><a href="bookmarks-ua.html">Вибране</a></div>
					<div class="item link left-icon history"><a class="link" href="/history-ua.html">Історія замовлень</a></div>
					<div class="item link left-icon response"><a class="link" href="/response-ua.html">Написати відгук</a></div>
					<div class="item link left-icon exit"><a class="link" href="/">Вийти</a></div>
				</div>
			</div>
			<div class="menu main" data-present>
				<div class="items">
					<div class="item" data-main-menu-item='catalogue'>
						<div class="name"><a href="/catalogue-ua.html">Каталог товарів</a></div>
						<div class="items">
							<div class="item">
								<div class="name"><a href="/products-groups-group-ua.html">Портали для каміна</a></div>
								<div class="items">
									<div class="item link"><a class="link" href="/products-group-ua.html">Класичні каміни</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Каміни у стилі кантрі</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Сучасні каміни</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Полиці для каміна</a></div>
								</div>
							</div>
							<div class="item">
								<div class="name"><a href="/products-groups-group-ua.html">Топки для камінів</a></div>
								<div class="items">
									<div class="item link"><a href="/products-group-ua.html">Топки для повітряного опалення</a></div>
									<div class="item link"><a href="/products-group-ua.html">Топки з водяним контуром</a></div>
								</div>
									<!--
									<div class="item">
										<div class="name"><a href="/products-group-ua.html">Топки для повітряного опалення</a></div>
										<div class="items">
											<div class="item link"><a href="/products-group-ua.html">Пряме скло</a></div>
											<div class="item link"><a href="/products-group-ua.html">Кутове скло</a></div>
											<div class="item link"><a href="/products-group-ua.html">Округле скло</a></div>
											<div class="item link"><a href="/products-group-ua.html">Призматичне скло</a></div>
											<div class="item link"><a href="/products-group-ua.html">Скло на три сторони</a></div>
											<div class="item link"><a href="/products-group-ua.html">Скло на дві сторони</a></div>
										</div>
									</div>
									-->
							</div>
							<div class="item">
								<div class="name"><a href="/products-groups-group-ua.html">Печі, гриль та фурнітура</a></div>
								<div class="items">
									<div class="item link"><a class="link" href="/products-group-ua.html">Опалювальні печі</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Опалювально-варильні печі</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Барбекю і гриль</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Пічна чавунна фурнітура</a></div>
								</div>
							</div>
							<div class="item">
								<div class="name"><a href="/products-groups-group-ua.html">Електричні каміни</a></div>
								<div class="items">
									<div class="item link"><a class="link" href="/products-group-ua.html">Камінокомплекти</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Електрокаміни топки, вставки</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Електрокаміни приставні</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Електрокаміни на стіну</a></div>
								</div>
							</div>
							<div class="item">
								<div class="name"><a href="/products-groups-group-ua.html">Біокаміни</a></div>
								<div class="items">
									<div class="item link"><a class="link" href="/products-group-ua.html">Біокаміни на основу</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Біокаміни настінні</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Пальники для біокаміна</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Аксесуари для біокаміна</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Біопаливо для каміна</a></div>
								</div>
							</div>
							<div class="item">
								<div class="name"><a href="/products-groups-group-ua.html">Гриль і барбекю</a></div>
								<div class="items">
									<div class="item link"><a href="/products-group-ua.html">Вугільні грилі</a></div>
									<div class="item link"><a href="/products-group-ua.html">Газові грилі</a></div>
									<div class="item link"><a href="/products-group-ua.html">Електричні грилі</a></div>
									<div class="item link"><a href="/products-group-ua.html">Аксесуари для гриля</a></div>
									<!--
									<div class="item">
										<div class="name"><a href="/products-group-ua.html">Вугільні грилі</a></div>
										<div class="items">
											<div class="item link"><a href="/products-group-ua.html">Портативні грилі</a></div>
											<div class="item link"><a href="/products-group-ua.html">Мобільні грилі</a></div>
											<div class="item link"><a href="/products-group-ua.html">Вбудовувані грилі</a></div>
											<div class="item link"><a href="/products-group-ua.html">Професійні грилі</a></div>
											<div class="item link"><a href="/products-group-ua.html">Чавунні грилі</a></div>
											<div class="item link"><a href="/products-group-ua.html">Керамічні грилі</a></div>
										</div>
									</div>
									<div class="item">
										<div class="name"><a href="/products-group-ua.html">Газові грилі</a></div>
										<div class="items">
											<div class="item link"><a href="/products-group-ua.html">Портативні грилі</a></div>
											<div class="item link"><a href="/products-group-ua.html">Мобільні грилі</a></div>
											<div class="item link"><a href="/products-group-ua.html">Вбудовувані грилі</a></div>
											<div class="item link"><a href="/products-group-ua.html">Професійні грилі</a></div>
										</div>
									</div>
									<div class="item link"><a href="/products-group-ua.html">Електричні грилі</a></div>
									<div class="item link"><a href="/products-group-ua.html">Аксесуари для гриля</a></div>
									<div class="item">
										<div class="name"><a href="/products-group-ua.html">Аксесуари для гриля</a></div>
										<div class="items">
											<div class="item link"><a href="/products-group-ua.html">Для вугільного гриля</a></div>
											<div class="item link"><a href="/products-group-ua.html">Для газового гриля</a></div>
											<div class="item link"><a href="/products-group-ua.html">Для електрогриля</a></div>
											<div class="item link"><a href="/products-group-ua.html">Підставки</a></div>
											<div class="item link"><a href="/products-group-ua.html">Чохли</a></div>
											<div class="item link"><a href="/products-group-ua.html">Вугілля і брикети</a></div>
											<div class="item link"><a href="/products-group-ua.html">Балони і шланги</a></div>
											<div class="item link"><a href="/products-group-ua.html">Тріска для копчення</a></div>
											<div class="item link"><a href="/products-group-ua.html">Прибори</a></div>
											<div class="item link"><a href="/products-group-ua.html">Деко і піддони</a></div>
											<div class="item link"><a href="/products-group-ua.html">Решітки і сітки</a></div>
											<div class="item link"><a href="/products-group-ua.html">Засоби для чистки</a></div>
											<div class="item link"><a href="/products-group-ua.html">Книги рецептів</a></div>
											<div class="item link"><a href="/products-group-ua.html">Термометри</a></div>
											<div class="item link"><a href="/products-group-ua.html">Шампури і вертели</a></div>
											<div class="item link"><a href="/products-group-ua.html">Фартуки і рукавиці</a></div>
										</div>
									</div>
									-->
								</div>
							</div>
							<div class="item">
								<div class="name"><a href="/products-groups-group-ua.html">Аксесуари для каміна</a></div>
								<div class="items">
									<div class="item link"><a class="link" href="/products-group-ua.html">Набори для каміна</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Дровниці для камина</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Іскрогасники</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Засоби для догляду за каміном</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Розпалювачі вогню, вологоміри</a></div>
								</div>
							</div>
							<div class="item">
								<div class="name"><a href="/products-groups-group-ua.html">Матеріали для монтажу</a></div>
								<div class="items">
									<div class="item link"><a class="link" href="/products-group-ua.html">Монтажні матеріали для каміна</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Дверці и скло на замовлення за розмірами</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Чавунні дверці для каміна</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Ремкомплекти для каміна</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Термостійка фарба</a></div>
								</div>
							</div>
							<div class="item">
								<div class="name"><a href="/products-groups-group-ua.html">Вентиляція, комини</a></div>
								<div class="items">
									<div class="item link"><a class="link" href="/products-group-ua.html">Вентиляційні решітки для камінів</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Системи повітряного опалення</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Вентилятори для камінів</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Димоходи з нержавіючої сталі</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Димохідні труби для камінів</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Керамічні димарі</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Дверцята, заслінки, засувки для димоходу</a></div>
								</div>
							</div>
							<div class="item">
								<div class="name"><a href="/products-groups-group-ua.html">Вуличні обігрівачі</a></div>
								<div class="items">
									<div class="item link"><a class="link" href="/products-group-ua.html">Газові обігрівачі</a></div>
									<div class="item link"><a class="link" href="/products-group-ua.html">Електричні обігрівачі</a></div>
								</div>
							</div>
							<div class="item link"><a href="/index-ua.html">Все для сауни</a></div>
						</div>
					</div>
					<div class="item" data-main-menu-item='actions'>
						<div class="name"><a href="/action-products-ua.html">Акції</a></div>
						<div class="items">
							<div class="item link"><a href="/action-products-group-ua.html">Гриль і барбекю</a></div>
							<div class="item link"><a href="/action-products-group-ua.html">Вентиляція, комини</a></div>
							<div class="item link"><a href="/action-products-group-ua.html">Портали для каміна</a></div>
							<div class="item link"><a href="/action-products-group-ua.html">Топки для камінів</a></div>
							<div class="item link"><a href="/action-products-group-ua.html">Печі та фурнітура</a></div>
							<div class="item link"><a href="/action-products-group-ua.html">Електричні каміни</a></div>
						</div>
					</div>
					<div class="item" data-main-menu-item='brands'>
						<div class="name"><a href="/brands-ua.html">Бренди</a></div>
						<div class="items">
							<div class="item link"><a href="/brand-ua.html">Comex</a></div>
							<div class="item link"><a href="/brand-ua.html">Dimplex</a></div>
							<div class="item link"><a href="/brand-ua.html">Gavryliv & Sons</a></div>
							<div class="item link"><a href="/brand-ua.html">Romotop</a></div>
							<div class="item link"><a href="/brand-ua.html">Schmid</a></div>
							<div class="item link"><a href="/brand-ua.html">Silca</a></div>
							<div class="item link"><a href="/brand-ua.html">Weber</a></div>
							<div class="item link"><a href="/brand-ua.html">Браво</a></div>
						</div>
					</div>
					<div class="item" data-main-menu-item='gallery'>
						<div class="name"><a href="/albums-groups-ua.html">Фотогалерея</a></div>
						<div class="items">
							<div class="item link"><a href="/albums-group-ua.html">Каміни</a></div>
							<div class="item link"><a href="/albums-group-ua.html">Димоходи</a></div>
							<div class="item link"><a href="/albums-group-ua.html">Мармур</a></div>
							<div class="item link"><a href="/albums-group-ua.html">Кахлі</a></div>
						</div>
					</div>
					<div class="item" data-main-menu-item='journal'>
						<div class="name"><a href="/journal-ua.html">Журнал</a></div>
						<div class="items">
							<div class="item link"><a href="/journal-group-ua.html">Каміни</a></div>
							<div class="item link"><a href="/journal-group-ua.html">Печі</a></div>
							<div class="item link"><a href="/journal-group-ua.html">Димоходи</a></div>
							<div class="item link"><a href="/journal-group-ua.html">Біокаміни</a></div>
							<div class="item link"><a href="/journal-group-ua.html">Топки</a></div>
							<div class="item link"><a href="/journal-group-ua.html">Електрокаміни</a></div>
							<div class="item link"><a href="/journal-group-ua.html">Барбекю і гриль</a></div>
						</div>
					</div>
					<div class="item" data-main-menu-item='services'>
						<div class="name"><a href="">Послуги</a></div>
						<div class="items">
							<div class="item link"><a href="">Проектування каміна</a></div>
							<div class="item link"><a href="">Монтаж каміна</a></div>
							<div class="item link"><a href="">Монтаж димоходів</a></div>
							<div class="item link"><a href="">Оренда гриля у Луцьку</a></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="layer with-shadow close-interface" data-layer-type="on-demand-authorization">
			<div class="content">
				<div class="close-interface" data-close-layer></div>
				<form action="/" name="form-user-on-demand" data-form-state="email-was-not-sending">
					<div class="text" data-form-state="email-was-not-sending">Будь ласка ідентифікуйте себе за допомогою електронної пошти</div>
					<div class="text" data-form-state="email-was-sending">На вказану адресу електронної пошти надіслано повідомлення.</div>
					<div class="" data-form-state="email-was-sending">Не прийшов лист?</div>
					<div class="form-input" data-form-state="email-was-not-sending">
						<label for="form-user-on-demand-email">Електронна пошта</label>
						<input class="block" type="email" name="form-user-on-demand-email" id="form-user-on-demand-email" autocomplete="off" required>
						<div class="input-error-text" data-error-type="1">Вкажіть адресу електронної пошти</div>
					</div>
					<button type="submit" class="button type1 green" onclick="this.parentElement.dataset.formState='email-was-sending'" data-form-state="email-was-not-sending">Отримати доступ</button>
					<button type="submit" class="button type1 green" onclick="this.parentElement.dataset.formState='email-was-not-sending'" data-form-state="email-was-sending">Надіслати ще раз</button>
				</form>
				<div class="text">або через соціальну мережу</div>
				<button type="button" class="button type1 facebook">Facebook</button>
				<button type="button" class="button type1 google">Google</button>
			</div>
		</div>
		<div class="shadow-layer"></div>
	</header>
